package model

import "time"

// CreateProjectRequest represents the JSON body for POST /api/v1/projects.
// Only the fields the client sends are included here (no server-generated fields).
//
// Validation rules (via Gin's binding tags):
//   - project_name: required
//   - description:  required
//   - icon:         required, must be one of the allowed Material Icon names
//   - teams:        optional, each entry must be a valid team key
//   - start_date:   optional, expected format: "YYYY-MM-DD"
type CreateProjectRequest struct {
	ProjectName string   `json:"project_name" binding:"required"`
	Description string   `json:"description" binding:"required"`
	Icon        string   `json:"icon" binding:"required,oneof=language smartphone cloud storage cloud-upload"`
	Teams       []string `json:"teams" binding:"omitempty,dive,oneof=backend frontend mobile qa uiux"`
	StartDate   string   `json:"start_date" binding:"omitempty"`
}

// Project represents a full project record in the database.
// Used as the API response after project creation.
//
// Server-generated fields (not sent by the client):
//   - ID, Status, WorkspaceID, CreatedBy, Progress, MemberCount, CreatedAt, UpdatedAt
type Project struct {
	ID          string    `json:"id" db:"id"`                     // UUID, auto-generated by PostgreSQL
	ProjectName string    `json:"project_name" db:"project_name"` // Name of the project
	Description string    `json:"description" db:"description"`   // Detailed project description
	Icon        string    `json:"icon" db:"icon"`                 // Material Icon name (e.g., "language", "smartphone")
	Teams       []string  `json:"teams" db:"teams"`               // Assigned team keys (e.g., ["backend", "frontend"])
	StartDate   *string   `json:"start_date,omitempty" db:"start_date"` // Optional project start date (YYYY-MM-DD)
	Status      string    `json:"status" db:"status"`             // Project status: "active", "planning", "on_hold", "completed"
	WorkspaceID string    `json:"workspace_id" db:"workspace_id"` // Auto-generated unique workspace identifier (e.g., "E-C-K1R2")
	CreatedBy   string    `json:"created_by" db:"created_by"`     // Registration UUID of the PM who created the project
	Progress    int       `json:"progress" db:"progress"`         // Completion percentage (0-100), starts at 0
	MemberCount int       `json:"member_count" db:"member_count"` // Number of assigned members, starts at 0
	CreatedAt   time.Time `json:"created_at" db:"created_at"`     // Record creation timestamp
	UpdatedAt   time.Time `json:"updated_at" db:"updated_at"`     // Last update timestamp
}
